### ISSUE TITLE
Archiving/distributing

### ISSUE THREAD

**Issue by blippy** [milancurcic/datetime-fortran#23]
The following issues were noted upon releasing 1.4.0:

@milancurcic said "<code>make dist</code> failed to install CONTRIBUTORS, README.md and LICENSE."

My response: I agree. I will look into this.

@zbeekman said "If you can find a way to get <code>make dist</code> to package the missing markdown files, you can just manually add the tarball generated by make dist as a release asset."

Yes. I think it is easy enough for me to do this.

I note additional packaging problems:
* git creates archives based on what is checked into the repo, which unfortunately does not include configure
* there can be mismatches between the version numbers in tags, the configure.ac file, and what's in src/lib/datetime.f90

I will look into these issues. If anyone has a good anser to this, then let me know.

**Comment by blippy** [comment]
The discussion above originally referenced in https://github.com/milancurcic/datetime-fortran/pull/22#issuecomment-175207961

**Comment by blippy** [comment]
@zbeekman also references the version mismatching at https://github.com/milancurcic/datetime-fortran/commit/d49af9ecefad7f213c539104146a7379e205052a#commitcomment-15688257

**Comment by blippy** [comment]
@milancurcic said "make dist failed to install CONTRIBUTORS, README.md and LICENSE."

Fixed by: 
https://github.com/blippy/datetime-fortran/commit/20e9709a16e7e7dadde8a7aac5e3008f700b726b

**Comment by blippy** [comment]
Added some consistency checking of versioning when you '''make dist'''. Making the distribution will fail if those checks are not satisified. 

See pull request: https://github.com/milancurcic/datetime-fortran/pull/26

Once patched, I think this issue can be closed.

**Comment by milancurcic** [comment]
I played a bit more with the make dist. See the files that come out of the tarball:

```
$ tar xzvf datetime-fortran-1.4.0.tar.gz 
datetime-fortran-1.4.0/
datetime-fortran-1.4.0/INSTALL
datetime-fortran-1.4.0/configure
datetime-fortran-1.4.0/Makefile.am
datetime-fortran-1.4.0/scrub-clean.sh
datetime-fortran-1.4.0/src/
datetime-fortran-1.4.0/src/tests/
datetime-fortran-1.4.0/src/tests/datetime_tests.f90
datetime-fortran-1.4.0/src/tests/Makefile.am
datetime-fortran-1.4.0/src/tests/Makefile.in
datetime-fortran-1.4.0/src/lib/
datetime-fortran-1.4.0/src/lib/mod_datetime.f90
datetime-fortran-1.4.0/src/lib/mod_strftime.f90
datetime-fortran-1.4.0/src/lib/Makefile.am
datetime-fortran-1.4.0/src/lib/mod_timedelta.f90
datetime-fortran-1.4.0/src/lib/mod_clock.f90
datetime-fortran-1.4.0/src/lib/Makefile.in
datetime-fortran-1.4.0/src/lib/mod_constants.f90
datetime-fortran-1.4.0/src/lib/datetime.f90
datetime-fortran-1.4.0/src/lib/datetime_module.mod
datetime-fortran-1.4.0/install-sh
datetime-fortran-1.4.0/Makefile.in
datetime-fortran-1.4.0/CONTRIBUTORS
datetime-fortran-1.4.0/mkdist.sh
datetime-fortran-1.4.0/configure.ac
datetime-fortran-1.4.0/aclocal.m4
datetime-fortran-1.4.0/datetime-fortran.pc.in
datetime-fortran-1.4.0/README.md
datetime-fortran-1.4.0/LICENSE
datetime-fortran-1.4.0/AUTHORS
datetime-fortran-1.4.0/missing
```
The `datetime_module.mod` shouldn't be in there. Is this easy to amend?

**Comment by blippy** [comment]
It looks as if all issues here are addresses, so I'll close it. 

Raise another issue if necessary.
