### ISSUE TITLE
Some cygwin/gfortran 4.9.3 test fails

### ISSUE THREAD

**Issue by blippy** [milancurcic/datetime-fortran#28]
Here are the test results for gfortran 4.9.3 on cygwin using v1.4.0:
<pre>
test empty datetime() constructor                                : FAIL
test semi-empty datetime() constructor                           : FAIL
test datetime + timedelta(milliseconds = 100)                    : FAIL
test datetime + timedelta(milliseconds = -100)                   : FAIL
test datetime + timedelta(seconds = 1)                           : FAIL
test datetime + timedelta(seconds = -1)                          : FAIL
test datetime + timedelta(minutes = 1)                           : FAIL
test datetime + timedelta(minutes = -1)                          : FAIL
test datetime + timedelta(hours = 1)                             : FAIL
test datetime + timedelta(hours = -1)                            : FAIL
test datetime + timedelta(days = 1)                              : FAIL
test datetime + timedelta(days = -1)                             : FAIL
test Seconds overflow in addMilliseconds (3000 milliseconds)     : FAIL
test Seconds overflow in addMilliseconds (-3000 milliseconds)    : FAIL
test Minutes overflow in addSeconds (360 seconds)                : FAIL
test Minutes overflow in addSeconds (-360 seconds)               : FAIL
test Hours overflow in addMinutes (360 minutes)                  : FAIL
test Hours overflow in addMinutes (-360 minutes)                 : FAIL
test Days overflow in addHours (72 hours)                        : FAIL
test Days overflow in addHours (-72 hours)                       : FAIL
-----------------------------------------------------------------------
test decrement datetime into January                             : FAIL
test decrement datetime into February                            : FAIL
test decrement datetime into March                               : FAIL
test decrement datetime into April                               : FAIL
test decrement datetime into May                                 : FAIL
test decrement datetime into June                                : FAIL
test decrement datetime into July                                : FAIL
test decrement datetime into August                              : FAIL
test decrement datetime into September                           : FAIL
test decrement datetime into October                             : FAIL
test decrement datetime into November                            : FAIL
test decrement datetime into December                            : FAIL
-----------------------------------------------------------------------
test datetime-datetime == timedelta(days = 1)                    : FAIL
test datetime-datetime == timedelta(hours = 1)                   : FAIL
test datetime-datetime == timedelta(minutes = 1)                 : FAIL
test datetime-datetime == timedelta(seconds = 1)                 : FAIL
test datetime-datetime == timedelta(milliseconds = 1)            : FAIL
-----------------------------------------------------------------------
test datetime == datetime                                        : FAIL
test datetime == datetime, timezone test 1                       : FAIL
test datetime == datetime, timezone test 2                       : FAIL
test datetime /= datetime                                        : PASS
test datetime > datetime                                         : FAIL
test datetime >= datetime (greater)                              : FAIL
test datetime >= datetime (equal)                                : FAIL
test datetime < datetime                                         : PASS
test datetime <= datetime (less)                                 : PASS
test datetime <= datetime (equal)                                : PASS
-----------------------------------------------------------------------
test datetime % isoformat, default separator                     : PASS
test datetime % isoformat, T separator                           : PASS
test datetime % isoformat, blank separator                       : PASS
-----------------------------------------------------------------------
test datetime % strftime                                         : PASS
test datetime % strptime                                         : FAIL
test strptime(datetime % strftime(fmt),fmt) == datetime          : FAIL
-----------------------------------------------------------------------
test datetime(2005,1,1) % isocalendar() == [2004,53,6]           : PASS
test datetime(2005,1,2) % isocalendar() == [2004,53,7]           : PASS
test datetime(2005,12,31) % isocalendar() == [2005,52,6]         : PASS
test datetime(2007,1,1) % isocalendar() == [2007,1,1]            : PASS
test datetime(2007,12,30) % isocalendar() == [2007,52,7]         : PASS
test datetime(2007,12,31) % isocalendar() == [2008,1,1]          : PASS
test datetime(2008,1,1) % isocalendar() == [2008,1,2]            : PASS
test datetime(2008,12,28) % isocalendar() == [2008,52,7]         : PASS
test datetime(2008,12,29) % isocalendar() == [2009,1,1]          : PASS
test datetime(2008,12,30) % isocalendar() == [2009,1,2]          : PASS
test datetime(2008,12,31) % isocalendar() == [2009,1,3]          : PASS
test datetime(2009,1,1) % isocalendar() == [2009,1,4]            : PASS
test datetime(2009,12,31) % isocalendar() == [2009,53,4]         : PASS
test datetime(2010,1,1) % isocalendar() == [2009,53,5]           : PASS
test datetime(2010,1,2) % isocalendar() == [2009,53,6]           : PASS
test datetime(2010,1,3) % isocalendar() == [2009,53,7]           : PASS
-----------------------------------------------------------------------
test datetime(1,1,1) is valid                                    : PASS
test datetime(0,1,1) is not valid                                : PASS
test datetime(-1,1,1) is not valid                               : PASS
test datetime(2014,1,1) is valid                                 : PASS
test datetime(2014,0,1) is not valid                             : PASS
test datetime(2014,1,0) is not valid                             : PASS
test datetime(2014,2,28) is valid                                : PASS
test datetime(2014,2,29) is not valid                            : PASS
test datetime(2012,2,29) is valid                                : PASS
test datetime(2012,3,31) is valid                                : PASS
test datetime(2012,3,32) is not valid                            : PASS
test datetime(2012,3,31,0,0,0) is valid                          : PASS
test datetime(2012,3,31,24,0,0) is not valid                     : PASS
test datetime(2012,3,31,0,60,0) is not valid                     : PASS
test datetime(2012,3,31,0,0,60) is not valid                     : PASS
test datetime(2012,3,31,0,0,0,1000) is not valid                 : PASS
-----------------------------------------------------------------------
test datetime % secondsSinceEpoch(), 0 seconds                   : PASS
test datetime % secondsSinceEpoch(), 1 hour                      : PASS
test datetime % secondsSinceEpoch(), -1 hour                     : PASS
-----------------------------------------------------------------------
test datetime % tzOffset(), +0000                                : PASS
test datetime % tzOffset(), -0330                                : PASS
test datetime % tzOffset(), +0545                                : PASS
-----------------------------------------------------------------------
test datetime % utc(), +0000                                     : FAIL
-----------------------------------------------------------------------
test datetime % weekday(), Wednesday                             : PASS
test datetime % weekday(), Thursday                              : PASS
test datetime % weekday(), Friday                                : PASS
test datetime % weekday(), Saturday                              : PASS
test datetime % weekday(), Sunday                                : PASS
test datetime % weekday(), Monday                                : PASS
test datetime % weekday(), Tuesday                               : PASS
-----------------------------------------------------------------------
test datetime % weekdayLong(), Wednesday                         : PASS
test datetime % weekdayLong(), Thursday                          : PASS
test datetime % weekdayLong(), Friday                            : PASS
test datetime % weekdayLong(), Saturday                          : PASS
test datetime % weekdayLong(), Sunday                            : PASS
test datetime % weekdayLong(), Monday                            : PASS
test datetime % weekdayLong(), Tuesday                           : PASS
-----------------------------------------------------------------------
test datetime % weekdayShort(), Wed                              : PASS
test datetime % weekdayShort(), Thu                              : PASS
test datetime % weekdayShort(), Fri                              : PASS
test datetime % weekdayShort(), Sat                              : PASS
test datetime % weekdayShort(), Sun                              : PASS
test datetime % weekdayShort(), Mon                              : PASS
test datetime % weekdayShort(), Tue                              : PASS
-----------------------------------------------------------------------
test datetime(2014,1,1) % yearday() == 1                         : PASS
test datetime(2014,2,1) % yearday() == 32                        : PASS
test datetime(2014,3,1) % yearday() == 60                        : PASS
test datetime(2014,4,1) % yearday() == 91                        : PASS
test datetime(2014,5,1) % yearday() == 121                       : PASS
test datetime(2014,6,1) % yearday() == 152                       : PASS
test datetime(2014,7,1) % yearday() == 182                       : PASS
test datetime(2014,8,1) % yearday() == 213                       : PASS
test datetime(2014,9,1) % yearday() == 244                       : PASS
test datetime(2014,10,1) % yearday() == 275                      : PASS
test datetime(2014,11,1) % yearday() == 305                      : PASS
test datetime(2014,12,1) % yearday() == 335                      : PASS
-----------------------------------------------------------------------
test timedelta empty constructor                                 : PASS
test timedelta % total_seconds(), milliseconds conversion        : PASS
test timedelta % total_seconds(), seconds conversion             : PASS
test timedelta % total_seconds(), minutes conversion             : PASS
test timedelta % total_seconds(), hours conversion               : PASS
test timedelta % total_seconds(), days conversion                : PASS
-----------------------------------------------------------------------
test datetime % utc() == num2date(date2num(datetime)) (now)      : FAIL
test datetime == num2date(date2num(datetime)) (overflowing month): FAIL
test datetime == num2date(date2num(datetime)) (overflowing year) : FAIL
-----------------------------------------------------------------------
test datetimeRange, day increment                                : PASS
test datetimeRange, hour increment                               : FAIL
test datetimeRange, minute increment                             : FAIL
test datetimeRange, second increment                             : FAIL
test datetimeRange, rounding test                                : FAIL
-----------------------------------------------------------------------
test isLeapYear(1) == F                                          : PASS
test isLeapYear(4) == T                                          : PASS
test isLeapYear(100) == F                                        : PASS
test isLeapYear(400) == T                                        : PASS
test isLeapYear(2000) == T                                       : PASS
test isLeapYear(2014) == F                                       : PASS
-----------------------------------------------------------------------
test daysInYear(2014) == 365                                     : PASS
test daysInYear(2012) == 366                                     : PASS
test daysInYear(2000) == 366                                     : PASS
test daysInYear(1900) == 365                                     : PASS
-----------------------------------------------------------------------
test daysInMonth(1,2014) == 31                                   : PASS
test daysInMonth(2,2014) == 28                                   : PASS
test daysInMonth(2,2012) == 29                                   : PASS
test daysInMonth(3,2014) == 31                                   : PASS
test daysInMonth(4,2014) == 30                                   : PASS
test daysInMonth(5,2014) == 31                                   : PASS
test daysInMonth(6,2014) == 30                                   : PASS
test daysInMonth(7,2014) == 31                                   : PASS
test daysInMonth(8,2014) == 31                                   : PASS
test daysInMonth(9,2014) == 30                                   : PASS
test daysInMonth(10,2014) == 31                                  : PASS
test daysInMonth(11,2014) == 30                                  : PASS
test daysInMonth(12,2014) == 31                                  : PASS
-----------------------------------------------------------------------
test clock % started == F (before tick)                          : PASS
test clock % started == T (after 1 tick)                         : PASS
test clock % stopped == F (after 1 tick)                         : FAIL
test clock % currentTime == clock % stopTime (after 24 ticks)    : FAIL
test clock % stopped == T (after 24 ticks)                       : PASS
test clock % started == F (after reset)                          : PASS
test clock % stopped == F (after reset)                          : PASS
test clock % currentTime == clock % startTime (after reset)      : FAIL
-----------------------------------------------------------------------
Ran a total of 170 tests.
114 tests PASSED,  56 tests FAILED.
</pre>

**Comment by milancurcic** [comment]
Awesome, the first test fails. These are usually easy to diagnose and resolve. :smile:

**Comment by blippy** [comment]
Note that commit 73a48cef8311829eb02d4342f4859a5071482886 fixes this. All tests now pass on cygwin.

Issue will therefore be closed.
