### ISSUE TITLE
Remove Makefile.ori files

### ISSUE THREAD

**Issue by blippy** [milancurcic/datetime-fortran#30]
The project has a number of files called <code>Makefile.ori</code>. These were the orginal makefiles. Now that autotools has been implemented successfully, they are redundant and can be removed from the project wherever they exist.

**Comment by zbeekman** [comment]
:+1:

**Comment by milancurcic** [comment]
Do we still want to implement the CMake building? Is it desirable in any way to have multiple build systems? If yes, it may make sense to keep the original Makefiles around for reference (module dependencies etc.). Or maybe I am just a hoarder. What do you think?

**Comment by zbeekman** [comment]
I see no real need to add a CMake build system. The only advantage that I can think of is that CMake provides an alternative to package-config for locating libraries, modules, etc. but I think CMake also knows how to use package-config.

As far as the old makefiles go, @milancurcic should be the ultimate judge of that. My vote is that if you're happy with the Makefiles that are generated by automake, then feel free to delete the old makefiles; they're still in the git history if anyone needs to go dig them up.

**Comment by blippy** [comment]
My advice: do not add CMake unless it's proven that we need to. Maintaining one build system is work enough.

**Comment by milancurcic** [comment]
Got it, just wanted to make sure.

**Comment by zbeekman** [comment]
yes, I agree with @blippy

**Comment by milancurcic** [comment]
Done. https://github.com/milancurcic/datetime-fortran/commit/1ba8b53371daa2875b64dd226452ebf01c5eb5a7

**Comment by blippy** [comment]
I know what you mean about the hoarding. What I generally do is put my old files into a directory called 'bak', which I sometimes clear out periodically.

My advice is to delete the ori files, though, as it just causes confusion with extra "stuff" everywhere. Remember, too, that the Makefile.am were largely just based on your original Makefiles, with some fancy tinsel sprinkled on to make autotools do some interesting extras. 

So they can be reconstructed if necessary.

**Comment by milancurcic** [comment]
> So they can be reconstructed if necessary.

In an afterthought, I realize they can also be resurrected from a past version of the branch.
