### ISSUE TITLE
configure is insensitive to FCFLAGS

### ISSUE THREAD

**Issue by milancurcic** [milancurcic/datetime-fortran#31]
Specifying FCFLAGS when running configure, for example:
```
$ FCFLAGS=-O3 FC=ifort ./configure
```
does not affect what flags are being used when running `make`. In fact, the flags are always `-Wall -O0 -C -fbacktrace`, which are the gfortran flags hardwired in `src/lib/Makefile.am`:

```
# Items needed specifically by autotools
AM_FCFLAGS = -Wall -O0 -C -fbacktrace
```
Specifying FC works as expected.

@blippy can you look into this at your convenience? Thanks!

**Comment by blippy** [comment]
yes. I'll look into it.

**Comment by blippy** [comment]
I've asked some questions on Stackexchange to see how autotools actually behaves. 

The documentation is VERY confusing.

**Comment by blippy** [comment]
I am discussing this issue over at http://stackoverflow.com/questions/35117315/so-what-is-am-fcflags , if you're interested. The consclusion so far is that I shouldn't set AM_FCFLAGS.

I will investigate further.

**Comment by blippy** [comment]
I "think" this is now fixed. I've done my own testing, and it looks OK.

It could definitely use some testing by others though, esp. where other compilers are concerned. I have not been able to perform configuration tests in the presence of alternative compilers.

**Comment by milancurcic** [comment]
Right, I believe this is fixed, I just forgot to close the issue few days ago. Thanks!!
