### ISSUE TITLE
INSTALL probably violates licensing/copyright

### ISSUE THREAD

**Issue by zbeekman** [milancurcic/datetime-fortran#34]
It is a straight up copy of a GNU boilerplate. #blameblippy (lol, I tease... thanks for all your hard work, @blippy)

**Comment by zbeekman** [comment]
OK, I'll eat my words: https://github.com/milancurcic/datetime-fortran/blob/master/INSTALL#L7-L10

**Comment by milancurcic** [comment]
LOL! :smile:
